CREATE TABLE [dbo].[UserBookRate]
(
	[Id] INT NOT NULL IDENTITY(1, 1),
	[UserId] INT NOT NULL,
	[BookId] INT NOT NULL,
	[Rate]	 SMALLINT NOT NULL,
	CONSTRAINT PK_UserBookRate		PRIMARY KEY (Id),
	CONSTRAINT FK_User_Rate_Id		FOREIGN KEY ([UserId])	REFERENCES Users(Id)	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_Book_Rate_Id		FOREIGN KEY ([BookId])	REFERENCES Books(Id)	ON UPDATE CASCADE ON DELETE CASCADE,
)
