CREATE TABLE [dbo].[Description]
(
	[ID] INT NOT NULL IDENTITY(1,1), 
	[Short] NVARCHAR(600) NOT NULL, 
    [Long] NVARCHAR(1500) NOT NULL,
	[BookId] INT NOT NULL,
	CONSTRAINT Pr_Key_DESC PRIMARY KEY([ID]),
	CONSTRAINT FK_BookId FOREIGN KEY([BookId]) REFERENCES Books(ID) ON DELETE CASCADE
)
