CREATE TABLE [dbo].[SellerBook]
(
	[Id] INT NOT NULL IDENTITY (1,1),
	[SellerId] INT NOT NULL,
	[BookId]   INT NOT NULL,
	CONSTRAINT PK_SellerBook PRIMARY KEY (Id),
	CONSTRAINT FK_Seller_Id FOREIGN KEY ([SellerId]) REFERENCES Sellers(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_Book_Id	FOREIGN KEY ([BookId])	 REFERENCES Books(Id)	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT UQ_UserId UNIQUE ([SellerId], [BookId])
)
